"""initial migrations

Revision ID: bf3f254d4865
Revises: 
Create Date: 2019-01-02 20:10:41.068373

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf3f254d4865'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_name', sa.String(length=32), nullable=True),
    sa.Column('desc', sa.String(length=128), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('create_time', sa.String(length=32), nullable=True),
    sa.Column('update_time', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_group_group_name'), 'group', ['group_name'], unique=True)
    op.create_table('role',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('role_name', sa.String(length=32), nullable=True),
    sa.Column('desc', sa.String(length=128), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('create_time', sa.String(length=32), nullable=True),
    sa.Column('update_time', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_name')
    )
    op.create_table('interface',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('api_name', sa.String(length=32), nullable=True),
    sa.Column('site', sa.String(length=32), nullable=True),
    sa.Column('uri', sa.String(length=64), nullable=True),
    sa.Column('group_id', sa.String(length=16), nullable=True),
    sa.Column('desc', sa.String(length=128), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('create_time', sa.String(length=32), nullable=True),
    sa.Column('update_time', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('site')
    )
    op.create_index(op.f('ix_interface_api_name'), 'interface', ['api_name'], unique=True)
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=16), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('is_manager', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('create_time', sa.String(length=32), nullable=True),
    sa.Column('update_time', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_interface_api_name'), table_name='interface')
    op.drop_table('interface')
    op.drop_table('role')
    op.drop_index(op.f('ix_group_group_name'), table_name='group')
    op.drop_table('group')
    # ### end Alembic commands ###
